apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rolling-update-demo
  template:
    metadata:
      labels:
        app: rolling-update-demo
    spec:
      containers:
      - name: rolling-update-demo
        image: us-east4-docker.pkg.dev/qwiklabs-gcp-02-b80793924be9/gke-rollback-task/rolling-update-demo:v1
        ports:
        - containerPort: 8080
